name: 'Plan Nginx Deployment'

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: 'Plan Nginx Deployment'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4

    - name: 'Set up Google Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: 'Authenticate to Google Cloud'
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > gcloud.json
        gcloud auth activate-service-account --key-file=gcloud.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: 'Get GKE credentials'
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }}

    - name: 'Dry-run Nginx Deployment'
      run: |
        kubectl apply -f nginx-deployment.yaml --dry-run=client

    - name: 'Dry-run Nginx Service'
      run: |
        kubectl apply -f nginx-service.yaml --dry-run=client
        