name: Terraform Apply K8S

on:
  push:
    branches:
      - main #k8s

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.7

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > /home/runner/gcloud.json
        gcloud auth activate-service-account --key-file=/home/runner/gcloud.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Init
      run: terraform -chdir=ejercicio-kubernetes/terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /home/runner/gcloud.json
        TF_VAR_credentials_file_path: /home/runner/gcloud.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Plan
      run: terraform -chdir=ejercicio-kubernetes/terraform plan -out=tfplan
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /home/runner/gcloud.json
        TF_VAR_credentials_file_path: /home/runner/gcloud.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Apply
      run: terraform -chdir=ejercicio-kubernetes/terraform apply -auto-approve
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /home/runner/gcloud.json
        TF_VAR_credentials_file_path: /home/runner/gcloud.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
