name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.7

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > $HOME/gcloud.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Init
      run: terraform -chdir=ejercicio-vm-02/terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud.json
        TF_VAR_credentials_file_path: $HOME/gcloud.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Plan
      run: terraform -chdir=ejercicio-vm-02/terraform plan -out=tfplan
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud.json
        TF_VAR_credentials_file_path: $HOME/gcloud.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Apply
      run: terraform -chdir=ejercicio-vm-02/terraform apply -auto-approve
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud.json
        TF_VAR_credentials_file_path: $HOME/gcloud.json
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
