name: 'Terraform Apply'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: 'Authenticate to Google Cloud'
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcloud.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud.json
          gcloud config set project $GCP_PROJECT_ID

      - name: 'Initialize Terraform'
        run: terraform -chdir=terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          TF_VAR_credentials_file_path: $HOME/gcloud.json
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Terraform Plan'
        run: terraform -chdir=terraform plan -out=plan.tfplan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          TF_VAR_credentials_file_path: $HOME/gcloud.json
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Terraform Apply'
        run: terraform -chdir=terraform apply -auto-approve plan.tfplan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          TF_VAR_credentials_file_path: $HOME/gcloud.json
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

